name = "auth-worker"
main = "src/worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Add D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "fragrance-collect-db"
database_id = "c4ec306a-6521-48ee-afaf-3c8871b40c24"

[vars]
# This is a placeholder. The actual client ID will be set as a secret.
GOOGLE_CLIENT_ID = "your_google_client_id_here"

# Observability configuration for consistent logging across deployments
[observability.logs]
enabled = true